---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/tags: rpm-build
  name: determine-build-number
spec:
  description: |
    Determine the build number for FESCo 3501 %buildrelease support.
    Queries the OCI registry for existing builds of the same NVR and
    determines the next build number. First build of an NVR has no
    build number suffix; rebuilds get +build1, +build2, etc.
  params:
    - description: Package name being built
      name: package-name
      type: string
    - name: specfile
      description: |
        Name of specfile when specfile doesn't have the same prefix name as
        package name. Default is null and package-name.spec is used.
      type: string
      default: "null"
    - description: The Trusted Artifact URI pointing to the artifact with the rpm deps and source.
      name: source-artifact
      type: string
    - name: ociStorage
      description: The OCI repository where build artifacts are stored.
      type: string
    - description: RPM Build environment OCI image to run scripts in
      name: script-environment-image
      type: string
    - name: enable-buildrelease
      description: |
        Enable FESCo 3501 buildrelease support. When false, this task
        returns empty results and skips registry queries.
      type: string
      default: "false"
  results:
    - name: build-number
      description: |
        The build number to use for this build. Empty string for first build
        of an NVR (no suffix), "1" for first rebuild (+build1), etc.
      type: string
    - name: base-nvr
      description: The base NVR (without build number suffix) extracted from the specfile.
      type: string
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - use
        - $(params.source-artifact)=/var/workdir/source
    - name: extract-nvr
      image: $(params.script-environment-image)
      script: |
        #!/bin/bash
        set -ex

        # Check if buildrelease is enabled
        if [ "$(params.enable-buildrelease)" != "true" ]; then
          echo "Buildrelease support is disabled, skipping NVR extraction"
          echo -n "" > /var/workdir/base-nvr.txt
          echo -n "disabled" > /var/workdir/buildrelease-status.txt
          exit 0
        fi

        echo -n "enabled" > /var/workdir/buildrelease-status.txt
        cd /var/workdir/source

        if test "$(params.specfile)" != "null" ; then
          specfile_name=$(params.specfile)
        else
          specfile_prefix=$(params.package-name)
          specfile_name="${specfile_prefix}.spec"
        fi

        # Extract NVR from specfile. The %buildrelease macro should produce
        # no suffix when buildnumber is not defined, giving us the base NVR.
        # We query for x86_64 as a representative architecture.
        BASE_NVR=$(rpm -q --specfile "$specfile_name" --queryformat '%{NAME}-%{VERSION}-%{RELEASE}\n' 2>/dev/null | head -1)

        if [ -z "$BASE_NVR" ]; then
          echo "ERROR: Could not extract NVR from specfile"
          exit 1
        fi

        echo "Base NVR: $BASE_NVR"
        echo -n "$BASE_NVR" > /var/workdir/base-nvr.txt
    - name: query-registry
      image: quay.io/konflux-ci/oras:latest@sha256:4542f5a2a046ca36653749a8985e46744a5d2d36ee10ca14409be718ce15129e
      script: |
        #!/bin/bash
        set -e

        # Check if buildrelease is enabled
        if [ "$(cat /var/workdir/buildrelease-status.txt)" = "disabled" ]; then
          echo "Buildrelease support is disabled, returning empty results"
          echo -n "" > "$(results.build-number.path)"
          echo -n "" > "$(results.base-nvr.path)"
          exit 0
        fi

        BASE_NVR=$(cat /var/workdir/base-nvr.txt)
        echo "Querying registry for existing RELEASED builds of: $BASE_NVR"

        # Normalize NVR for OCI compatibility (tildes and plus signs are not allowed in tags)
        NVR_NORMALIZED="${BASE_NVR//\~/_}"
        NVR_NORMALIZED="${NVR_NORMALIZED//+/_}"

        # The registry URL pattern used by import-to-quay
        REGISTRY_URL="$(params.ociStorage)"

        # Set up auth
        select-oci-auth "$REGISTRY_URL" > "$HOME/auth.json" 2>/dev/null || true

        # Function to check if an image has a release marker attached (OCI referrers)
        # Returns 0 if released, 1 if not
        is_released() {
          local image_ref="$1"
          local referrers

          # Use oras discover to find attached artifacts of the release marker type
          referrers=$(oras discover \
            --registry-config "$HOME/auth.json" \
            --artifact-type "application/vnd.konflux.rpm.released.v1" \
            --format json \
            "$image_ref" 2>/dev/null || echo '{"manifests":[]}')

          # Check if any release markers were found
          local count
          count=$(echo "$referrers" | jq '.manifests | length' 2>/dev/null || echo "0")

          if [ "$count" -gt 0 ]; then
            return 0  # Released
          else
            return 1  # Not released
          fi
        }

        # List all tags from the registry
        TAGS_OUTPUT=$(skopeo list-tags --authfile "$HOME/auth.json" "docker://${REGISTRY_URL}" 2>/dev/null || echo '{"Tags": []}')

        echo "Registry response: $TAGS_OUTPUT"

        # Find tags matching our NVR pattern:
        # - Exact match: nvr-<NVR_NORMALIZED> (first build, no suffix)
        # - Rebuild match: nvr-<NVR_NORMALIZED>+build<N> or nvr-<NVR_NORMALIZED>_build<N>
        # Note: + may be encoded as _ in OCI tags

        MAX_BUILD_NUM=0
        FOUND_RELEASED_BASE=false

        # Parse tags using jq
        MATCHING_TAGS=$(echo "$TAGS_OUTPUT" | jq -r ".Tags // [] | .[] | select(startswith(\"nvr-${NVR_NORMALIZED}\"))" 2>/dev/null || true)

        if [ -n "$MATCHING_TAGS" ]; then
          while IFS= read -r tag; do
            echo "Found matching tag: $tag"

            # Construct full image reference
            IMAGE_REF="${REGISTRY_URL}:${tag}"

            # Check if this build has been released (has release marker attached)
            if is_released "$IMAGE_REF"; then
              echo "  -> RELEASED (has release marker)"

              # Check for _buildN in the tag (rebuilds)
              # Tag format: nvr-<NVR>[_buildN].<pipelinerun-name>
              # Extract build number from patterns like: nvr-foo-1.0-1.fc42_build3.run-xyz
              if [[ "$tag" =~ _build([0-9]+)\. ]]; then
                BUILD_NUM="${BASH_REMATCH[1]}"
                echo "  -> Found released build number: $BUILD_NUM"
                if [ "$BUILD_NUM" -gt "$MAX_BUILD_NUM" ]; then
                  MAX_BUILD_NUM=$BUILD_NUM
                fi
              else
                # No _buildN means this is a base build (first build of this NVR)
                FOUND_RELEASED_BASE=true
                echo "  -> Base NVR released (first build, no _buildN suffix)"
              fi
            else
              echo "  -> Not released (no release marker), skipping"
            fi
          done <<< "$MATCHING_TAGS"
        fi

        # Determine next build number based on RELEASED builds only
        if [ "$MAX_BUILD_NUM" -gt 0 ]; then
          # Released rebuilds exist, increment from max
          NEXT_BUILD_NUM=$((MAX_BUILD_NUM + 1))
          echo "Found released rebuilds, next build number: $NEXT_BUILD_NUM"
        elif [ "$FOUND_RELEASED_BASE" = true ]; then
          # Released base exists but no released rebuilds, this is first rebuild
          NEXT_BUILD_NUM=1
          echo "Released base build exists, this is first rebuild: $NEXT_BUILD_NUM"
        else
          # No released builds found, this is first build (no suffix)
          NEXT_BUILD_NUM=""
          echo "No released builds found, this is first build (no suffix)"
        fi

        # Write results
        echo -n "$NEXT_BUILD_NUM" > "$(results.build-number.path)"
        echo -n "$BASE_NVR" > "$(results.base-nvr.path)"

        echo "=== Results ==="
        echo "Base NVR: $BASE_NVR"
        echo "Build number: ${NEXT_BUILD_NUM:-'(empty - first build)'}"
  volumes:
    - name: workdir
      emptyDir: {}
